// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_AuthErrorNotification.cpp"
#include "UVLADIE3JM/moc_GitHubClient.cpp"
#include "UVLADIE3JM/moc_MainWindow.cpp"
#include "UVLADIE3JM/moc_NotificationItemWidget.cpp"
#include "UVLADIE3JM/moc_SettingsDialog.cpp"
